splash = false

wallpaper {
    monitor = DP-2
    path = ~/.config/hypr/wallpapers/red-j.jpg
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/wallpapers/red-j.jpg
    fit_mode = cover
}
