monitorv2 {
    output = DP-2
    mode = 2560x1440@164.84
    position = 1920x0
    scale = 1.0
    transform = 0
    bitdepth = 10
    cm = srgb
    sdr_eotf = srgb
    vrr = 3
}

monitorv2 {
    output = HDMI-A-1
    mode = 1920x1080@74.97
    position = 0x0
    scale = 1.0
    transform = 0
    bitdepth = 8
    cm = srgb
    sdr_eotf = srgb
    vrr = 0
}

render {
    cm_auto_hdr = 0
    direct_scanout = 0
}
