exec-once = waybar
exec-once = hyprpaper
exec-once = swaync
exec-once = systemctl --user start hyprpolkitagent
exec-once = [workspace 8 silent] alacritty -e btop
exec-once = nm-applet
exec-once = steam -silent
exec-once = signal-desktop --start-in-tray
exec-once = discord --start-minimized
exec-once = polychromatic-tray-applet
exec-once = razer-cli -d "Razer Huntsman V3 Pro" -e static -c FF0000
exec-once = sleep 5 && /home/diver/OpenRGB/usr/bin/OpenRGB --startminimized
exec = hyprshade on vibrance
