exec-once = waybar
exec-once = hyprpaper
exec-once = swaync
exec-once = systemctl --user start hyprpolkitagent
exec-once = [workspace 8 silent] alacritty -e btop
exec-once = steam -silent
exec-once = signal-desktop --start-in-tray
exec-once = sleep 5 && 1password --silent
# exec-once = polychromatic-tray-applet
exec-once = sleep 5 && razer-cli -d "Razer Huntsman V3 Pro" -e static -c FF0000
exec-once = sleep 13 && /home/diver/OpenRGB/usr/bin/OpenRGB --startminimized
exec-once = sleep 7 && protonvpn-app --start-minimized
exec = hyprshade on vibrance
