exec-once = waybar
exec-once = hyprpaper
exec-once = swaync
exec-once = systemctl --user start hyprpolkitagent
exec-once = [workspace 8 silent] alacritty -e btop
exec-once = nm-applet
exec-once = steam -silent
exec-once = signal-desktop --start-in-tray
exec-once = discord --start-minimized
exec-once = polychromatic-tray-applet
exec-once = razer-cli -e static -c FF0000
exec-once = ~/OpenRGB.AppImage --appimage-extract-and-run -m static -c FF0000
exec = hyprshade on vibrance
