windowrule = suppressevent maximize, class:.*
windowrule = nofocus,       class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule = stayfocused, class:(Rofi)
windowrule = float, center, class:(Code|Electron), floating:1
windowrule = tile, class:(Code|Electron), title: ^(Open .*)$

# GAMES
$games = ^(steam_app.*|pioneergame.exe)$
windowrule = workspace 2,       class:$games
windowrule = noanim,            class:$games
windowrule = noblur,            class:$games
windowrule = noshadow,          class:$games
windowrule = noborder,          class:$games
windowrule = rounding 0,        class:$games
windowrule = fullscreen,        class:$games
windowrule = immediate,         class:$games
