windowrule = suppress_event maximize, match:class .*
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
windowrule = stay_focused on, match:class (Rofi)
windowrule = center on, match:class (Code|Electron), match:float 1
windowrule = tile on, match:class (Code|Electron), match:title ^(Open .*)$

# GAMES
$antiCheat = ^(.*EasyAntiCheat.*|)$
$steamProc = ^(steam_app_.*)$

# Send Away Game AntiCheat Prompts
windowrule = tag +launcher, match:class $steamProc, match:title $antiCheat
windowrule = workspace 8 silent, match:tag launcher
windowrule = no_follow_mouse on, match:tag launcher

# Send Games to correct workspace
windowrule = tag +game, match:class $steamProc, match:tag negative:launcher
windowrule = workspace 2, match:tag game
windowrule = content game, match:tag game
windowrule = fullscreen_state 2 2, match:tag game, match:title negative:Warframe
windowrule = decorate off, match:tag game
windowrule = rounding 0, match:tag game
windowrule = render_unfocused on, match:tag game
windowrule = immediate on, match:tag game
