windowrule = suppress_event maximize, match:class .*
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
windowrule = stay_focused on, match:class (Rofi)
windowrule = center on, match:class (Code|Electron), match:float 1
windowrule = tile on, match:class (Code|Electron), match:title ^(Open .*)$

#
windowrule = no_screen_share on, match:title (.*Private.*)

# GAMES
$antiCheat = ^(.*EasyAntiCheat.*|.*BattlEye.*|)$
$steamProc = ^(steam_app_.*|Albion-Online|cs2|Warhammer.*)$

# Send Away Game AntiCheat Prompts
windowrule = tag +launcher, match:class $steamProc, match:title $antiCheat
windowrule = workspace 8 silent, match:tag launcher
windowrule = no_follow_mouse on, match:tag launcher

# Send Games to correct workspace
windowrule = tag +game, match:class $steamProc, match:tag negative:launcher
windowrule = workspace 4 silent, match:tag game
windowrule = content game, match:tag game
windowrule = fullscreen_state 2 2, match:tag game, match:title negative:Warframe
windowrule = decorate off, match:tag game
windowrule = rounding 0, match:tag game
windowrule = render_unfocused on, match:tag game
windowrule = immediate on, match:tag game
windowrule = no_blur on, match:tag game
windowrule = no_shadow on, match:tag game
windowrule = border_size 0, match:tag game
windowrule = opaque on, match:tag game
windowrule = no_anim on, match:tag game
windowrule = confine_pointer on, match:tag game
