# WorkSpaces
workspace = 1, monitor:DP-2, persistent:true, default:true
workspace = 2, monitor:DP-2, persistent:true
workspace = 3, monitor:DP-2, persistent:true
workspace = 4, monitor:DP-2, persistent:true, gapsin:0, gapsout:0, border:false, rounding:false, decorate:false, shadow:false
workspace = 5, monitor:HDMI-A-1, persistent:true, default:true
workspace = 6, monitor:HDMI-A-1, persistent:true
workspace = 7, monitor:HDMI-A-1, persistent:true
workspace = 8, monitor:HDMI-A-1, persistent:true
